# fly.toml app configuration file generated for temp-surreal on 2023-06-23T20:19:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "temp-surreal"
primary_region = "ams"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
